name: main
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Cache Poetry
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test

  # TODO: Figure out why this is failing with the following error:
  #   Waiting for remote builder fly-builder-fragrant-smoke-9554...
  #   Error failed to fetch an image or build from source: error connecting to docker: remote builder app unavailable
  #   WARN Remote builder did not start in time. Check remote builder logs with `flyctl logs -a fly-builder-fragrant-smoke-9554`

  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     # This step checks out a copy of your repository.
  #     - uses: actions/checkout@v2
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - run: flyctl deploy --remote-only
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
